services:
  frontend:
    build:
      context: ./frontend
    image: monitoring-frontend:latest
    container_name: frontend
    volumes:
      - frontend-data:/srv

  api_server:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.api
    image: monitoring-api:latest
    container_name: api_server
    environment:
      - API_PORT=5000
      - DATABASE_URL=${DATABASE_URL}

  collector:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.collector
    image: monitoring-collector:latest
    container_name: collector
    environment:
      - API_PORT=5000
      - API_ADDRESS=http://api_server
    volumes:
      - collector-data:/app
    depends_on:
      - api_server

  caddy:
    image: caddy:2.11.2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - frontend-data:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frontend
      - api_server

volumes:
  caddy-config:
  caddy-data:
  collector-data:
  frontend-data:
