FROM rust:1.94 AS builder 
WORKDIR /app 

COPY . . 
RUN cargo fetch 
RUN cargo build --release --bin collector

FROM debian:13-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists
WORKDIR /app 
COPY --from=builder /app/target/release/collector .
CMD [ "./collector" ] 


